language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
    rustup component add clippy-preview rustfmt;
    cargo clippy -- -D clippy::all;
    cargo fmt --all -- --check;
    fi

notifications:
  email:
    on_success: never